substitutions:
  friendly_name: rf433mhz

packages:
  device_base: !include device_base_esp32.yaml

remote_receiver:
  pin:
    number: GPIO21
    inverted: True
    mode: INPUT_PULLUP
  dump: all
  # dump: rc_switch

  tolerance: 50%
  filter: 10us
  idle: 4ms
  buffer_size: 2kb

# remote_receiver:
#   pin: D0
#   dump: all
#   # Settings to optimize recognition of RF devices
#   tolerance: 50%
#   filter: 250us
#   idle: 4ms
#   buffer_size: 2kb
