substitutions:
  friendly_name: fumeextractor
  friendly_id: fumeextractor

# ESP8266
packages:
  device_base: !include device_base_8266_nodemcu_nonetwork.yaml
  # device_base: !include device_base_8266_nodemcu.yaml

# PWM FAN OUTPUT
output:
  - platform: esp8266_pwm
    pin: D7
    id: fanny
    frequency: 25kHz

# POTENTIOMETER
sensor:
  - platform: adc
    name: "fanpot"
    id: fanpot
    pin: A0
    raw: true
    accuracy_decimals: 1
    update_interval: 100ms
    filters:
      - calibrate_linear:
        - 0 -> 0.0
        - 1024 -> 1000
      - delta: 10
      - multiply: 0.001
    on_value:
      then:
        - output.set_level:
            id: fanny
            level: !lambda return x; //id(fanpot).state;

number:
  # deadband_threshold
  - platform: template
    name: $friendly_name pwmoutput
    icon: mdi:chart-bell-curve
    restore_value: true
    min_value: 0
    max_value: 1
    step: 0.1
    set_action:
      lambda: id(fanny).set_level( x );