substitutions:
  friendly_name: "Garage Door"
  friendly_id: garagedoor

packages:
  device_base: !include device_base_esp32.yaml

# Sensors: closed = magnetic, open = no presence.
# Top Sensor (measures door closed)
# Bottom Sensor (measures door is open)
# Top (closed) sensor is closed, DOOR IS CLOSED DOWN
# Bottom (open) sensor is closed, DOOR HAS OPENED UP
# Both sensors are open, DOOR IS MOVING
# Both sensors are closed, BUG, rare, they're both in contact.

cover:
  - platform: template
    name: "Garage Door v2"
    id: garage_door_v2
    device_class: garage

    open_action:
      - switch.turn_on: garage_door_relay
      - lambda: 
          id(garage_door_v2).current_operation = COVER_OPERATION_OPENING;

    close_action:
      - switch.turn_on: garage_door_relay
      - lambda: 
          id(garage_door_v2).current_operation = COVER_OPERATION_CLOSING;

    stop_action:
      - switch.turn_on: garage_door_relay
    optimistic: false
    assumed_state: false

    lambda: |-
      if (!id(garage_open_sensor).state) {
        return COVER_OPEN;

      }
      else if (!id(garage_closed_sensor).state) {
        return COVER_CLOSED;
      }
      return 1;
      // } else {
      //   return COVER_OPEN;
      // }

switch:
  - platform: gpio
    internal: true
    pin: 
      number: GPIO23
      inverted: true
    name: "Garage Door"
    id: garage_door_relay
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - delay: 1000ms
      - switch.turn_off: garage_door_relay


# Sensors: closed = magnetic, open = no presence.
# Top Sensor (measures door closed)
# Bottom Sensor (measures door is open)
# Top (closed) sensor is closed, DOOR IS CLOSED DOWN
# Bottom (open) sensor is closed, DOOR HAS OPENED UP
# Both sensors are open, DOOR IS MOVING
# Both sensors are closed, BUG, rare, they're both in contact.

# Define Hall Effect Sensors
binary_sensor:
  - platform: gpio
    name: "Garage Door Open (Bottom) Hall Sensor"
    id: garage_open_sensor
    device_class: garage_door
    #internal: true
    pin: 
      number: GPIO32
      mode:
        pullup: true
        input: true
    filters:
      - delayed_off: 500ms
    on_release:
      then:
        - cover.template.publish:
            id: garage_door_v2
            state: !lambda |-
              id(garage_door_v2).current_operation = COVER_OPERATION_IDLE;
              return COVER_OPEN;

  - platform: gpio
    name: "Garage Door Closed (Top) Hall Sensor"
    id: garage_closed_sensor
    device_class: garage_door
    #internal: true
    pin: 
      number: GPIO33
      mode:
        pullup: true
        input: true
    filters:
      - delayed_off: 500ms
    
    on_release:
      then:
        - cover.template.publish:
            id: garage_door_v2
            state: !lambda |-
              id(garage_door_v2).current_operation = COVER_OPERATION_IDLE;
              return COVER_CLOSED;
              
