substitutions:
  friendly_name: basic

esphome:
  name: $friendly_name

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp8266:
  board: nodemcuv2
  framework:
    version: recommended
  
logger:
api:
ota:
captive_portal:

text_sensor:
  # Send IP Address
  - platform: wifi_info
    ip_address:
      name: $friendly_name IP Address

  # Send Uptime in raw seconds
  - platform: template
    name: $friendly_name Uptime
    id: uptime_human
    icon: mdi:clock-start
    update_interval: 5s


# Sensors that the ESPhome unit is capable of reporting
sensor:
  - platform: wifi_signal
    name: $friendly_name WiFi Signal
    update_interval: 5s
  
  - platform: uptime
    internal: true
    id: uptime_sensor
    update_interval: 5s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            # Custom C++ code to generate the result
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

binary_sensor:
  - platform: status
    name: "Node Status"
    id: system_status

time:
  - platform: homeassistant
    id: esptime